version: "3"
services:
  app:
    image: delowerhasandh/spohire-frontend
    container_name: frontend-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
